# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku5p-ffvb676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/2019/OMD/template/template.cache/wt [current_project]
set_property parent.project_path D:/Projects/2019/OMD/template/template.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kcu116:part0:1.4 [current_project]
set_property ip_output_repo d:/Projects/2019/OMD/template/template.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/blake512.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/g_function_1.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/mux2_1.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/mux2_1_1024.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/mux2_1_512.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/omd_controller.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/perm.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/ram256x512.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v00.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v01.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v02.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v03.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v04.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v05.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v06.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v07.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v08.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v09.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v10.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v11.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v12.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v13.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v14.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/reg_64_v15.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/reg_en_1024.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/reg_en_512.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/imports/new/round_f_controller.vhd
  D:/Projects/2019/OMD/template/template.srcs/sources_1/new/encrypt.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top encrypt -part xcku5p-ffvb676-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef encrypt.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file encrypt_utilization_synth.rpt -pb encrypt_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
